docs_dir: doc/book
site_dir: doc/html
nav:
    - 首页: index.md
    - "MVC 教程":
      - "Zend Framework 入门":
          - 概述: getting-started/overview.md
          - 骨架应用: getting-started/skeleton-application.md
          - 模块: getting-started/modules.md
          - 路由和控制器: getting-started/routing-and-controllers.md
          - 数据库及模型: getting-started/database-and-models.md
          - 表单和操作: getting-started/forms-and-actions.md
          - 结论: getting-started/conclusion.md
      - "为 zend-mvc 应用使用单元测试": unit-testing.md
      - "添加 zend-navigation 到专辑模块": navigation.md
      - "添加 zend-paginator 到专辑模块": pagination.md
      - "深入教程":
          - "介绍博客模块": in-depth-guide/first-module.md
          - "模块和服务管理器": in-depth-guide/models-and-servicemanager.md
          - "不同数据库的方案": in-depth-guide/preparing-databases.md
          - "SQL 抽象和对象 Hydration": in-depth-guide/zend-db-sql-zend-hydrator.md
          - "Understanding the Router": in-depth-guide/understanding-routing.md
          - "Making Use of Forms and Fieldsets": in-depth-guide/zend-form-zend-form-fieldset.md
          - "添加或删除数据": in-depth-guide/data-binding.md
          - "复审博客模块": in-depth-guide/review.md
      - "Advanced Configuration": advanced-config.md
      - Internationalization: i18n.md
    - "Component Tutorials":
      - "Setting Up A Database Adapter": db-adapter.md
      - "Using the EventManager": event-manager.md
    - Migration:
        - "To Version 3":
            - Overview: migration/to-v3/overview.md
            - Components: migration/to-v3/components.md
            - Applications: migration/to-v3/application.md
site_name: tutorials
site_description: "Zend Framework Tutorials"
repo_url: 'https://gitee.com/MushRoom/zf-tutorials'
copyright: 'Copyright (c) 2016 <a href="http://www.zend.com/">Zend Technologies USA Inc.</a>'
site_url: 'https://zendframeowrk.laminas.org.cn/tutorials'
theme:
  name: null
  custom_dir: 'zf-mkdoc-theme/theme'
extra:
  scripts: scripts-8d7ae56abf.js
  styles: styles-5cfabd53ee.css
